title: Andrew Joshua Olayemi
logo: My picture zoom.JPG
description: ðŸ‘‹ Hi, Iâ€™m Andrew Joshua Olayemi (MSc, CDMP) â€” a data-driven marketer and analyst with 2+ years of experience in data analytics, performance marketing, and campaign optimization.

ðŸ’¡ I specialize in turning raw data into actionable insights using SQL, Power BI, and Excel, and have delivered measurable business outcomes such as:

ðŸš€ Generating $130K+ revenue in 10 months through lean-budget Meta ad campaigns.

ðŸ“Š Improving lead quality by 35% and CRM-qualified entries by 40% with insight-led targeting.

ðŸ“ˆ Boosting engagement by 30%+ through data-backed content strategies.

ðŸ”§ My toolkit includes:

Data Analytics: SQL (DDL, DML, DQL, Window Functions), Power BI (DAX, Power Query, Dashboards), Excel (Pivot Tables, VBA, What-if Analysis)

Digital Marketing: Meta Ads, Google Analytics, SEO tools (SEMRush, SimilarWeb), CRM optimization

Business Skills: Process improvement, stakeholder management, gap analysis, reporting

ðŸŽ¯ Iâ€™m passionate about blending analytics and marketing to solve business challenges, enhance decision-making, and drive measurable growth.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
